version: "1.0"

services:
  mongodb:
    image: mongo:4.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongodb
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      - 3000:3000
    environment:
      - DB_HOST=mongodb
      - DB_USER=root
      - DB_PASSWORD=123
      - DB_NAME=test-svara
      - DB_PORT=27017
    stdin_open: true
    tty: true

volumes:
  db:
